panes: [loadavg, weather, sghaze, datetime]
plugins:
  loadavg:
    bg: colour154
    fg: colour16
  sghaze:
    fg: colour82
  datetime:
    fg: colour250
    bg: colour239
  weather:
    city_code: "1062617"
